export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';

export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';

export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';

export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';

export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';

export const CREATE_SIGNIN = 'CREATE_SIGNIN';

export const CREATE_GET_LOGUSER = 'CREATE_GET_LOGUSER';

export const CREATE_GET_PERMISSION = 'CREATE_GET_PERMISSION';

export const LOAD_SPONSORS_SUCCESS = 'LOAD_SPONSORS_SUCCESS';

export const LOAD_SPONSORS_SELECT_LIST_SUCCESS = 'LOAD_SPONSORS_SELECT_LIST_SUCCESS';

export const CREATE_SPONSOR_SUCCESS = 'CREATE_SPONSOR_SUCCESS';

export const UPDATE_SPONSOR_SUCCESS = 'UPDATE_SPONSOR_SUCCESS';

export const DELETE_SPONSOR_SUCCESS = 'DELETE_SPONSOR_SUCCESS';

export const LOAD_TRIALS_SUCCESS = 'LOAD_TRIALS_SUCCESS';

export const LOAD_TRIALS_SELECT_LIST_SUCCESS = 'LOAD_TRIALS_SELECT_LIST_SUCCESS';

export const CREATE_TRIAL_SUCCESS = 'CREATE_TRIAL_SUCCESS';

export const UPDATE_TRIAL_SUCCESS = 'UPDATE_TRIAL_SUCCESS';

export const DELETE_TRIAL_SUCCESS = 'DELETE_TRIAL_SUCCESS';

export const COMPELETE_TRIAL_SUCCESS = 'COMPELETE_TRIAL_SUCCESS';

export const GET_TRIAL_BY_ID_SUCCESS = 'GET_TRIAL_BY_ID_SUCCESS';

export const LOAD_DRUG_TYPES_SUCCESS = 'LOAD_DRUG_TYPES_SUCCESS';

export const LOAD_DSMBS_SUCCESS = 'LOAD_DSMBS_SUCCESS';

export const LOAD_DOSAGE_SUCCESS = 'LOAD_DOSAGE_SUCCESS';

export const LOAD_FREQUENCY_SUCCESS = 'LOAD_FREQUENCY_SUCCESS';

export const LOAD_Patient_LIST= 'LOAD_Patient_LIST';

export const LOAD_ALL_PATIENT_LIST= 'LOAD_ALL_PATIENT_LIST';

export const LOAD_PHASE_PATIENT_LIST = 'LOAD_PHASE_PATIENT_LIST';

export const LOAD_FALLOUT_PATIENT_LIST = 'LOAD_FALLOUT_PATIENT_LIST';

export const LOAD_USER_LIST= 'LOAD_USER_LIST';

export const LOAD_USER_ROLE= 'LOAD_USER_ROLE';

export const LOAD_TIMEZONE_LIST= 'LOAD_TIMEZONE_LIST';

export const CREATE_USERS= 'CREATE_USERS';

export const DELETE_USER_SUCCESS= 'DELETE_USER_SUCCESS';

export const UPDATE_USER_SUCCESS= 'UPDATE_USER_SUCCESS';

export const DELETE_PATIENT_SUCCESS= 'DELETE_PATIENT_SUCCESS';

export const DISABLE_USER_SUCCESS= 'DISABLE_USER_SUCCESS';

export const LOAD_COUNTRY_LIST= 'LOAD_COUNTRY_LIST';

export const LOAD_STATE_LIST= 'LOAD_STATE_LIST';

export const CREATE_CHANGE_PASSWORD= 'CREATE_CHANGE_PASSWORD';

export const LOAD_TRIALS_STATUS_SUCCESS= 'LOAD_TRIALS_STATUS_SUCCESS';

export const LOAD_PATIENT_NOTIFICATION_LIST= 'LOAD_PATIENT_NOTIFICATION_LIST';

export const LOAD_DEVICE_SUCCESS = 'LOAD_DEVICE_SUCCESS';

export const GET_PIE_CHART_STATUS_SUCCESS = 'GET_PIE_CHART_STATUS_SUCCESS';

export const LOAD_SENSOR_DATA_SUCCESS = 'LOAD_SENSOR_DATA_SUCCESS';

export const LOAD_CASSANDRA_DATA_SUCCESS = 'LOAD_CASSANDRA_DATA_SUCCESS';

export const LOAD_DEVICE_GROUP_LIST = 'LOAD_DEVICE_GROUP_LIST';

export const CREATE_DEVICE = 'CREATE_DEVICE';

export const LOAD_ALL_DEVICE_LIST_DATASUCCESS = 'LOAD_ALL_DEVICE_LIST_DATASUCCESS';

export const DELETE_DEVICE_SUCCESS = 'DELETE_DEVICE_SUCCESS';

export const UPDATE_DEVICE_SUCCESS = 'UPDATE_DEVICE_SUCCESS';

export const LOAD_USER_ROLE_NAME = 'LOAD_USER_ROLE_NAME';

export const LOAD_SPONSORS_SELECT_LIST_DSMB_SUCCESS = 'LOAD_SPONSORS_SELECT_LIST_DSMB_SUCCESS';

export const LOAD_CRO_COORDINATOR_SUCCESS = 'LOAD_CRO_COORDINATOR_SUCCESS';

export const LOAD_SIDE_EFFECTS_SUCCESS = 'LOAD_SIDE_EFFECTS_SUCCESS';

export const CREATE_SIDE_EFFECT_SUCCESS = 'CREATE_SIDE_EFFECT_SUCCESS';

export const UPDATE_SIDE_EFFECT_SUCCESS = 'UPDATE_SIDE_EFFECT_SUCCESS';

export const DELETE_SIDE_EFFECT_SUCCESS = 'DELETE_SIDE_EFFECT_SUCCESS';

export const GET_METRICS_STATUS_SUCCESS = 'GET_METRICS_STATUS_SUCCESS';

export const LOAD_ACTIVE_DSMBS_SUCCESS = 'LOAD_ACTIVE_DSMBS_SUCCESS';

export const GET_DSMB_METRICS_STATUS_SUCCESS = 'GET_DSMB_METRICS_STATUS_SUCCESS';

export const LOAD_TRIAL_MILESTONE_STATUS_SUCCESS = 'LOAD_TRIAL_MILESTONE_STATUS_SUCCESS';

export const LOAD_VITAL_DATA_SUCCESS = 'LOAD_VITAL_DATA_SUCCESS';

export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';

export const SET_NOTIFICATION_LIST = 'SET_NOTIFICATION_LIST';

export const LOAD_ALL_ENROLLED_PATIENT_LIST = 'LOAD_ALL_ENROLLED_PATIENT_LIST';

export const LOAD_ALL_ENROLLED_PATIENT_TRIAL = 'LOAD_ALL_ENROLLED_PATIENT_TRIAL';