export default {
  courses: [],
  authors: [],
  ajaxCallsInProgress: 0,
  sponsors: [],
  sponsorsSelectList:[],
  drugTypes: [],
  dsmbs: [],
  dosages: [],
  trials: [],
  trial:[],
  trialsSelectList:[],
  trial: [],
  frequencies:[],
  users:[],
  patients:[],
  phasePatients :[],
  falloutPatients :[],
  stateList:[],
  userPassword:[],
  notificationList:[],
  deviceList:[],
  piechartStatus :[],
  sensorData : [],
  cassandraData : [],
  deviceData: [],
  croCoordinator:[],
  sideEffects : [],
  allpatients : [],
  vitalDataList : [],
  enrolledTrialPatientData: [],
  enrolledTrial:[]
};
